### ISSUE TITLE
cast_list() corrupts Windows paths

### ISSUE THREAD

**Issue by ctenglish** [mjdorma/funconf#2]
When a list value is used for a config entry, eg:

```
devenv:
  solutions: []
```

funcconf uses `shlex.split()` to "cast" the command line argument to a list. This behaves badly for Windows paths, for example the following command line:

`xbuild devenv --solutions packages\\Solution.sln`

results in a "solutions" value of `packagesSolution.sln` rather than the expected `packages\Solution.sln`.
## Suggestions

Change the `cast_list` function to use the `posix=False` argument to `shlex.split()`, introducted in Python 2.6.

i.e.

```
value = shlex.splite(value, posix=False)
```

This works for me, but turning off Posix compatibility may be a bad thing. An alternative would be to handle backslashes in the input string as a special case, eg:

```
value = value.replace('\\', 'xxBACKSLASHxx')
value = [v.replace('xxBACKSLASHxx', '\\') for v in shlex.split(value)]
```

**Comment by mjdorma** [comment]
Thanks for your solution @ctenglish.  I opted to implicitly replace \ to maintain a consistent split across platforms.  shlex support for a windows seemed to fizzle in this issue http://bugs.python.org/issue1724822 ...

Cheers :+1:
